import type { NextPage } from 'next'
import Head from 'next/head'
import { usePresence } from '../../../packages/presence-react/dist'

const Home: NextPage = () => {
  const p = usePresence()
  console.log('p:', p);
  
  return (
    <div>
      <Head>
        <title>Presence Whthin Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home
