import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useRef } from 'react';
import { useMyState, usePeers, useUpdateMyState } from '../lib/presence.config';

const Home: NextPage = () => {
  const peers = usePeers();
  const myState = useMyState();
  const updateMyState = useUpdateMyState();
  const inputRef = useRef<any>();

  console.log('my state:', myState);
  console.log('peers:', peers);

  const clickHandle = () => {
    const el = inputRef.current;
    if (el) {
      updateMyState({ name: el.value });
      el.value = '';
    }
  };

  return (
    <div>
      <Head>
        <title>Presence Within Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>name:{myState.name}</div>
        <input ref={inputRef} />
        <div>other user:</div>
        <div>
          {peers.map(({ id, name }: any) => (
            <div key={id}>
              {id}-{name}
            </div>
          ))}
        </div>
      </div>
      <button onClick={clickHandle}>update name</button>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  await (async () => new Promise((resolve) => setTimeout(resolve, 4000)))();
  return {
    props: {},
  };
}
